language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
before_script:
  - gem install bundler
  - "cd spec/dummy"
  - "RAILS_ENV=test bundle exec rake db:migrate --trace"
  - "cd ../.."
script: "bundle exec rspec"
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

addons:
  code_climate:
    repo_token: 95524d49aeaaaaa1e6f48d4ce653776f38693ff023d836c54e57d4da0c9e70a2